version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

env:
  BASE_URL: '{{.BASE_URL | default "example.com"}}'
  LANGUAGE: '{{.LANGUAGE | default "en-us"}}'
  TITLE: '{{.TITLE | default "Hello, World!"}}'
  THEME: '{{.THEME | default "ananke"}}'
  PORT: '{{.PORT | default "1313"}}'

vars:

includes:
  docker:
    taskfile: ./taskfiles/docker.yml

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list

  printenv:
    desc: "Print variables"
    summary: "Useful for debugging .env files / environment variables"
    cmds:
      - |
        echo {{.BASE_URL}}
        echo {{.LANGUAGE}}
        echo {{.TITLE}}
        echo {{.THEME}}
        echo {{.PORT}}
    silent: true

  install-devbox:
    desc: "Install devbox"
    cmds:
      - |
        if ! [[ $(command -v devbox 2>/dev/null) ]]; then
          curl -fsSL https://get.jetify.com/devbox | bash
        fi
    run: once
    silent: true

  pull:
    desc: "Update git submodules"
    cmds:
      - git submodule update --init --recursive
      - git pull --recurse-submodules
    ignore_error: true

  install:
    desc: "Install project dependencies"
    cmds:
      - mise install
    ignore_error: true

  gen-config:
    desc: "Generate Hugo TOML configuration"
    dir: "{{.ROOT_DIR}}"
    cmds:
      - |
        cat > hugo.toml << 'EOF'
        baseURL = 'https://{{.BASE_URL}}/'
        languageCode = '{{.LANGUAGE}}'
        title = '{{.TITLE}}'
        theme = '{{.THEME}}'

        [params]
        custom_css = ["css/custom.css"]
        custom_js = ["js/custom.js"]
        EOF
    preconditions:
      - test -f "{{.ROOT_DIR}}/hugo.toml"

  build:
    desc: "Build the site"
    dir: "{{.ROOT_DIR}}"
    cmds:
      - mise exec -- hugo --minify --enableGitInfo
    sources:
      - "**/*.md"
      - "**/*.css"
      - "**/*.js"
    generates:
      - "{{.ROOT_DIR}}/public/**"

  run:
    desc: "Run the development server"
    dir: "{{.ROOT_DIR}}"
    cmds:
      - mise exec -- hugo server --bind="0.0.0.0:{{.PORT}}"

  deploy:
    desc: "Copy static files to the caddy directory"
    deps: ["build"]
    dir: "{{.ROOT_DIR}}"
    cmds:
      - |
        sudo rsync -arvhW \
          --no-compress \
          --progress \
          --stats \
          --delete \
          public/ ${CADDY_DIR}
